blueprints/auth.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session
from exts import mail
from flask_mail import Message
from flask import request
import string
import random
from models import EmailCaptchaModel, db, UserModel
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash


bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                print('该邮箱未注册')
                return redirect(url_for('auth.login'))
            if check_password_hash(user.password, password):
                # cookie中不适合存储太多的数据，只适合存储少量的数据，比如用户id
                # session: 服务器存储用户数据的地方
                # flask中的session，是经过加密后存储在cookie中的
                session['user_id'] = user.id
                return redirect('/')
            else:
                print('密码错误')
                return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return redirect(url_for('auth.login'))


# GET: 从服务器获取数据
# POST: 向服务器提交数据
@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        # 验证用户提交的数据
        # 表单验证：flask-wtf：wtforms
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return redirect(url_for('auth.register'))


@bp.route('/logout')
def logout():
    session.clear()
    return redirect('/')


@bp.route('/captcha/email', methods=['GET'])
def get_email_captcha():
    # /captcha/email/<email>
    # /captcha/email?email=xxx@xx.com
    email = request.args.get('email')
    # 4/6位随机数
    source = string.digits * 4
    captcha = random.sample(source, 4)
    captcha = ''.join(captcha)
    # I/O操作 Input/Output
    msg = Message(subject='KMZ问答注册验证码', recipients=[email], body=f'您的验证码为{captcha}，请在5分钟内完成注册。')
    mail.send(msg)
    # memcache/redis
    # 用数据库表的方式存储
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({'code':200, 'msg': '', 'data': None})


@bp.route('/mail/test')
def mail_test():
    msg = Message(subject='test', recipients=['qq1318342521@126.com'], body='test')
    mail.send(msg)
    return 'success'

blueprints/qa.py
from flask import Blueprint, request, render_template, g, redirect, url_for
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from decroators import login_required

bp = Blueprint("qa", __name__, url_prefix='/')


@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template('index.html', questions=questions)


@bp.route("/qa/public", methods=['GET', 'POST'])
@login_required
def public_question():
    if request.method == 'GET':
        return render_template('ask.html')
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect('/')
        else:
            print(form.errors)
            return redirect(url_for('qa.public_question'))


@bp.route("/qa/detail/<qa_id>")
def question_detail(qa_id):
    question = QuestionModel.query.get(qa_id)
    return render_template('questions_details.html', question=question)


# @bp.route("/answer/public", methods=['POST'])
@bp.post("/answer/public")
@login_required
def public_answer():
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        answer = AnswerModel(content=content, question_id=question_id, author=g.user)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('qa.question_detail', qa_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for('qa.question_detail', qa_id=request.form.get('question_id')))

templates/ask.html
{% extends 'base.html' %}

{% block title %}KMZ问答 - 发布问答{% endblock %}

{% block head %}{% endblock %}

{% block body %}
    <h1>提问</h1>
    <!-- 提问表单 -->
    <form method="post">
      <input type="text" name="title" placeholder="问题标题" required>
      <textarea name="content" placeholder="问题描述" required></textarea>
      <button type="submit">提交问题</button>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  {% block head %}
  {% endblock %}
</head>
<body>

  <nav class="navbar">
    <ul>
      <li><a href="{{ '/' }}">首页</a></li>
      <li><a href="{{ url_for('qa.public_question') }}">提问</a></li>
      <li>   |   </li>
        {% if user %}
            <li>{{user.username}}</li>
            <li><a href="{{ url_for('auth.logout') }}">退出登录</a></li>
        {% else %}
        <li><a href="{{ url_for('auth.login') }}">登录</a></li>
        <li><a href="{{ url_for('auth.register') }}">注册</a></li>
        {% endif %}
    </ul>
  </nav>

  <div class="content">
      {% block body %}{% endblock %}
  </div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}KMZ问答 - 首页{% endblock %}

{% block head %}
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
        }
        main {
            padding: 20px;
        }
        section {
            margin-bottom: 20px;
        }
        .qa {
            list-style-type: none;
            padding: 0;
        }
        .qa li {
            background-color: #f1f1f1;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 10px;
        }
        .qa li:hover {
            background-color: #ddd;
        }
        li a {
            color: #333;
            text-decoration: none;
            font-size: 16px;
        }
        li a:hover {
            color: #0077cc;
        }
        #content {
            margin-top: 10px;
            margin-bottom: 10px;
            font-size: 13px;
        }
        .title {
            font-size: 18px;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>欢迎来到KMZ问答</h1>
    <p>这里是问题和答案的平台。</p>
    <main>
        <section>
            <h2>最新问题</h2>
            {% for question in questions %}
                <ul class="qa">
                    <li>
                        <div style="float: left; width: 75px; height: 75px; background-image: url('static/profile_photo.png');
                        background-size: contain; border-radius: 50%"></div>
                        <a class="title" href="{{url_for('qa.question_detail', qa_id=question.id)}}">{{question.title}}</a>
                        <p id="content">{{question.content}}</p>
                        <p id="content">{{ question.author_username }}</p>
                        <p id="content">{{ question.create_time }}</p>
                    </li>
                </ul>
            {% endfor %}
        </section>
    </main>



    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}KMZ问答 - 登录{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<h1>登录</h1>
<!-- 登录表单 -->
<form method="post">
    <input type="text" name="email" placeholder="邮箱" required>
    <input type="password" name="password" placeholder="密码" required>
    <button type="submit">登录</button>
</form>
{% endblock %}

templates/questions_details.html
{% extends 'base.html' %}

{% block title %}{{ question.title }}{% endblock %}

{% block head %}{% endblock %}

{% block body %}
    <h1>问题详情</h1>
    <!-- 问题内容 -->
    <div class="question">
        <h2>{{question.title}}</h2>
        <p>{{question.content}}</p>
        <p>提问者：{{question.author.username}}</p>
        <p>提问时间：{{question.create_time}}</p>
    </div>
    <!-- 回答列表 -->
    <div class="answers">
        <h2>回答</h2>
        {% for answer in question.answers %}
        <div class="answer">
            <p>{{ answer.content }}</p>
            <p>回答者：{{ answer.author.username }}</p>
            <p>回答时间：{{ answer.create_time }}</p>
        </div>
        {% endfor %}
    </div>
    <!-- 回答表单 -->
    <form action="{{url_for('qa.public_answer')}}" method="post">
        <textarea name="content" placeholder="输入你的回答" required></textarea>
        <input type="hidden" name="question_id" value="{{ question.id }}">
        <button type="submit">提交回答</button>
    </form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}KMZ问答 - 注册{% endblock %}

{% block head %}
      <script src="{{ url_for('static', filename='jquery.3.7.1.min.js') }}"></script>
      <script src="{{ url_for('static', filename='register.js') }}"></script>
{% endblock %}

{% block body %}
<h1>注册</h1>
<!-- 注册表单 -->
<form action="/auth/register" method="post">
    <input type="text" name="email" placeholder="邮箱" required>
    <div class="verification">
        <input class="code" type="text" name="captcha" placeholder="请输入验证码" required>
        <button type="button" id="captcha-btn">获取验证码</button>
    </div>
    <input type="text" name="username" placeholder="用户名" required>
    <input type="password" name="password" placeholder="密码" required>
    <input type="password" name="password_confirm" placeholder="确认密码" required>
    <input class="register" type="submit" value="立即注册">
</form>
{% endblock %}